# Customize Airflow values as needed
dags:
  persistence:
    enabled: true
    storageClassName: ebs-sc
    size: 1Gi

executor: CeleryExecutor

airflow:
  webserver:
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"

  scheduler:
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"